version: '3.8'

services:
  gateway:
    build:
      context: . # This refers to the swisper/ directory
      dockerfile: Dockerfile.gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/app/gateway
      - ./orchestrator:/app/orchestrator
      - ./contract_engine:/app/contract_engine
      - ./tool_adapter:/app/tool_adapter
      - ./haystack_pipeline:/app/haystack_pipeline
      - ./prompt_preprocessor.py:/app/prompt_preprocessor.py
      - ./tests:/app/tests
      - ./docs:/app/docs
      - ./contract_templates:/app/contract_templates
      - ./schemas:/app/schemas
      - ./db_data:/app/db_data                     # ✅ Correct shelve storage directory
      - ./tmp:/app/tmp                             # For contract artifacts
    working_dir: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}           # From your .env file
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    command: uvicorn gateway.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    # Optional: enable if you want to load env vars from file automatically
    # env_file:
    #   - .env