FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . . # Copies the content of swisper/ (build context) to /app
# CMD ["uvicorn", "gateway.main:app", "--host", "0.0.0.0", "--port", "8000"]
