# swisper/contract_engine/__init__.py
from .haystack_components import MockGoogleShoppingComponent, SimplePythonRankingComponent, ProductSelectorComponent
from .contract_pipeline import create_product_selection_pipeline
