name: Swisper CI

on: [push, pull_request]

defaults:
  run:
    working-directory: ./swisper # Ensures commands run in swisper/ context

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Add linters (e.g., flake8 or ruff) and pytest execution here later
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # - name: Test with pytest
    #   run: |
    #     pip install pytest
    #     pytest
